### ISSUE TITLE
Custom strategy on Vue project

### ISSUE THREAD

**Issue by frwebdev** [ricveal/scribere#14]
I am using library  without any particular problems, implementing it in a Vue project as described in your documentation

What I can't do is insert a custom strategy to pass into the options.

Would you be so kind as to let me understand with an example where the strategy should be written and how it should be inserted in the options?

Thank you

**Comment by ricveal** [comment]
You can follow the implementation of the default strategy: [ConsoleLoggerStrategy](https://github.com/ricveal/scribere/blob/master/src/logger/strategies/consoleLoggerStrategy.ts)
You should create a class which implements the LoggerStrategy interface.

Then, you should follow the steps described on the [Vue chapter](https://github.com/ricveal/scribere#vue) of the README.

If your custom strategy is called `CustomStrategy`:

```
- src
|-- main.js
|-- logger
  |-- index.js
  |-- install.js
```

`index.js`

```js
import install from './install'

const Log4Vue = {installed: false}
Log4Vue.install = install

export default Log4Vue
```

`install.js`

```js
import {Logger} from 'scribere'
// import CustomStrategy implementation

// Default options
const defaultOptions = {
  prefix: new Date().toISOString(),
  severity: 0
}

export default function install(Vue, options = undefined) {
  if (this.installed) return
  const logger = options ? new Logger(options, new CustomStrategy()) : new Logger(defaultOptions, new CustomStrategy())
  // The logger will be accesible in this.$console
  Vue.prototype.$console = logger
  Vue.console = logger
  window.logger = logger
  this.installed = true
}
```

`main.js`

```js
import Vue from 'vue'
import VueLogger from './logger'

Vue.use(VueLogger)

new Vue({
  //... options
})
```

**Comment by frwebdev** [comment]
Working with a vue project in javascript, i have had trouble trying to extend the class with typescript, as indicated by you.
I then changed the class to javascript, bypassing the typing

This works for me

```
- src
|-- main.js
|-- logger
  |-- strategy
         |-- CustomStrategy.js
  |-- index.js
  |-- install.js
```


`CustomStrategy.js`

``` javascript
export default class CustomStrategy  {
  constructor() {}
  // eslint-disable-next-line class-methods-use-this
  trace(
    data,
    level,
    instance
  ) {
    const prefix =
      typeof instance.prefix === 'function'
        ? instance.prefix()
        : instance.prefix
    // Format: PREFIX :: LEVEL :: data
    // eslint-disable-next-line no-console
    console[level](`[${prefix} :: ${level}] ::`.toUpperCase(), JSON.stringify(data, null, 4))
  }
}

```
`install.js`

``` javascript
import {Logger} from 'scribere'
import  CustomStrategy from './strategy/CustomStrategy'

// Default options
const defaultOptions = {
  prefix: new Date().toISOString(),
  severity: 0
}
 
export default function install(Vue, options = undefined) {
  if (this.installed) return
 const logger = options ? new Logger(options, new CustomStrategy()) : new Logger(defaultOptions, new CustomStrategy())
  // The logger will be accesible in this.$console
  Vue.prototype.$console = logger
  Vue.console = logger
  window.logger = logger
  this.installed = true
}
```

**Comment by ricveal** [comment]
So the problem you report was with Typescript, right?
It's important to notice that any custom strategy should implement the `LoggerStrategy` interface. May be that the problem?

I close the issue but, please, feel free to re-open it providing extra information (ideally a repo/codesandbox) to reproduce the problem you describe if you want.

Thank you!
